version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install  # Install all dependencies
      - npm install react-scripts --save-dev  # Ensure react-scripts is installed

  pre_build:
    commands:
      - echo "Pre-build check"
      - npm list react-scripts || echo "react-scripts not found, attempting reinstall"

  build:
    commands:
      - echo "Starting build process..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no

