version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci  # Uses package-lock.json for clean install

  pre_build:
    commands:
      - echo "Pre-build phase - verifying installation"
      - npm list react-scripts || echo "react-scripts not found, checking package.json"

  build:
    commands:
      - echo "Starting build process..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully!"
      - ls -la

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
