version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install  # Ensures dependencies are installed
      - npm list react-scripts || echo "react-scripts not found!"

  build:
    commands:
      - echo "Starting build process..."
      - npm run build || (echo "Build failed, checking react-scripts..." && npm list react-scripts)

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
